### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by Etiene** [starwing/luaiter#1]
Hi, firstly, thanks for the great project.
Secondly, is this open source? I cant see a license file.
Cheers!

**Comment by starwing** [comment]
Sorry for missing, this is the same as Lua's License, same as MIT license.

I will add this notice to README file. thanks :)

**Comment by Etiene** [comment]
Awesome! Thanks for that! 👍 
I do suggest still adding a small licence file though, because then it shows on github header and it's super easy to identify immediately! :)

**Comment by starwing** [comment]
Okay, I'll try it
